// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vibruvwwwxqtagmlkodq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpYnJ1dnd3d3hxdGFnbWxrb2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjEyODIsImV4cCI6MjA2MDIzNzI4Mn0.7s_NqBKDjAvtfr7GKPPMhqizUh9VbAfOY4j2lrE3p7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);